<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\syncfusion.common.desktop.props" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Syncfusion.MarkdownDemos.WinUI</AssemblyName>
    <RootNamespace>Syncfusion.MarkdownDemos.WinUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Model\**" />
    <EmbeddedResource Remove="ViewModel\**" />
    <None Remove="Model\**" />
    <None Remove="ViewModel\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Package.appxmanifest" />
    <None Remove="Properties\Default.rd.xml" />
    <None Remove="syncfusion.markdowndemos.winui_TemporaryKey.pfx" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\Markdown\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.DocIORenderer.NET" Version="34.2.2" />
    <PackageReference Include="Syncfusion.PresentationRenderer.NET" Version="34.2.2" />
    <PackageReference Include="Syncfusion.XlsIORenderer.NET" Version="34.2.2" />
    <PackageReference Include="Syncfusion.Pdf.Imaging.NET" Version="34.2.2" />
    <PackageReference Include="Syncfusion.MetafileRenderer.NET" Version="34.2.2" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../common/Syncfusion.DemosCommon.WinUI_lib_Net10.csproj" />
  </ItemGroup>
  <Import Project="..\targets\MultiTargeting_Net10.targets" />
</Project>