<Project>
<ItemGroup>
	<Compile Include="..\Markdown\Helpers\SaveHelper.cs">
		<Link>Markdown\Helpers\SaveHelper.cs</Link>
	</Compile>
    <Compile Include="..\Markdown\SamplesConfiguration.cs">
		<Link>Markdown\SamplesConfiguration.cs</Link>
	</Compile>
    <Compile Include="..\Markdown\Views\CreateMarkdown.xaml.cs">
		<Link>Markdown\Views\CreateMarkdown.xaml.cs</Link>
      <DependentUpon>..\Markdown\Views\CreateMarkdown.xaml</DependentUpon>
    </Compile>
	 <Compile Include="..\Markdown\Views\WordToMarkdown.xaml.cs">
		<Link>Markdown\Views\WordToMarkdown.xaml.cs</Link>
      <DependentUpon>..\Markdown\Views\WordToMarkdown.xaml</DependentUpon>
    </Compile>
	<Compile Include="..\Markdown\Views\MarkdownToWord.xaml.cs">
		<Link>Markdown\Views\MarkdownToWord.xaml.cs</Link>
      <DependentUpon>..\Markdown\Views\MarkdownToWord.xaml</DependentUpon>
    </Compile>
	<Compile Include="..\Markdown\Views\ExcelToMarkdown.xaml.cs">
		<Link>Markdown\Views\ExcelToMarkdown.xaml.cs</Link>
      <DependentUpon>..\Markdown\Views\ExcelToMarkdown.xaml</DependentUpon>
    </Compile>
	<Compile Include="..\Markdown\Views\MarkdownToExcel.xaml.cs">
		<Link>Markdown\Views\MarkdownToExcel.xaml.cs</Link>
      <DependentUpon>..\Markdown\Views\MarkdownToExcel.xaml</DependentUpon>
    </Compile>
	<Compile Include="..\Markdown\Views\MarkdownToPPTX.xaml.cs">
		<Link>Markdown\Views\MarkdownToPPTX.xaml.cs</Link>
      <DependentUpon>..\Markdown\Views\MarkdownToPPTX.xaml</DependentUpon>
    </Compile>
	<Compile Include="..\Markdown\Views\PPTXToMarkdown.xaml.cs">
		<Link>Markdown\Views\PPTXToMarkdown.xaml.cs</Link>
      <DependentUpon>..\Markdown\Views\PPTXToMarkdown.xaml</DependentUpon>
    </Compile>
	<Compile Include="..\Markdown\Views\MarkdownToHTML.xaml.cs">
		<Link>Markdown\Views\MarkdownToHTML.xaml.cs</Link>
      <DependentUpon>..\Markdown\Views\MarkdownToHTML.xaml</DependentUpon>
    </Compile>
	<Compile Include="..\Markdown\Views\MarkdownToPDF.xaml.cs">
		<Link>Markdown\Views\MarkdownToPDF.xaml.cs</Link>
      <DependentUpon>..\Markdown\Views\MarkdownToPDF.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
<ItemGroup>
	   <Page Include="..\Markdown\Views\WordToMarkdown.xaml">
		<Link>Markdown\Views\WordToMarkdown.xaml</Link>
	    <Generator>MSBuild:Compile</Generator>
		<SubType>Designer</SubType>
	  </Page>
	  <Page Include="..\Markdown\Views\MarkdownToWord.xaml">
		<Link>Markdown\Views\MarkdownToWord.xaml</Link>
	    <Generator>MSBuild:Compile</Generator>
		<SubType>Designer</SubType>
	  </Page>
	  <Page Include="..\Markdown\Views\CreateMarkdown.xaml">
		<Link>Markdown\Views\CreateMarkdown.xaml</Link>
	    <Generator>MSBuild:Compile</Generator>
		<SubType>Designer</SubType>
	  </Page>
	  <Page Include="..\Markdown\Views\ExcelToMarkdown.xaml">
		<Link>Markdown\Views\ExcelToMarkdown.xaml</Link>
	    <Generator>MSBuild:Compile</Generator>
		<SubType>Designer</SubType>
	  </Page>
	  <Page Include="..\Markdown\Views\MarkdownToExcel.xaml">
		<Link>Markdown\Views\MarkdownToExcel.xaml</Link>
	    <Generator>MSBuild:Compile</Generator>
		<SubType>Designer</SubType>
	  </Page>
	  <Page Include="..\Markdown\Views\MarkdownToHTML.xaml">
		<Link>Markdown\Views\MarkdownToHTML.xaml</Link>
	    <Generator>MSBuild:Compile</Generator>
		<SubType>Designer</SubType>
	  </Page>
	  <Page Include="..\Markdown\Views\MarkdownToPDF.xaml">
		<Link>Markdown\Views\MarkdownToPDF.xaml</Link>
	    <Generator>MSBuild:Compile</Generator>
		<SubType>Designer</SubType>
	  </Page>
	  <Page Include="..\Markdown\Views\MarkdownToPPTX.xaml">
		<Link>Markdown\Views\MarkdownToPPTX.xaml</Link>
	    <Generator>MSBuild:Compile</Generator>
		<SubType>Designer</SubType>
	  </Page>
	  <Page Include="..\Markdown\Views\PPTXToMarkdown.xaml">
		<Link>Markdown\Views\PPTXToMarkdown.xaml</Link>
	    <Generator>MSBuild:Compile</Generator>
		<SubType>Designer</SubType>
	  </Page>
  </ItemGroup>
<ItemGroup>
	<Content Include="..\Markdown\Assets\Markdown\WordToMarkdown_cs.txt">
		<Link>Markdown\Assets\Markdown\WordToMarkdown_cs.txt</Link>
	</Content>
	<Content Include="..\Markdown\Assets\Markdown\MarkdownToWord_cs.txt">
		<Link>Markdown\Assets\Markdown\MarkdownToWord_cs.txt</Link>
	</Content>
	<Content Include="..\Markdown\Assets\Markdown\CreateMarkdown_cs.txt">
		<Link>Markdown\Assets\Markdown\CreateMarkdown_cs.txt</Link>
	</Content>
	<Content Include="..\Markdown\Assets\Markdown\ExcelToMarkdown_cs.txt">
		<Link>Markdown\Assets\Markdown\ExcelToMarkdown_cs.txt</Link>
	</Content>
	<Content Include="..\Markdown\Assets\Markdown\MarkdownToExcel_cs.txt">
		<Link>Markdown\Assets\Markdown\MarkdownToExcel_cs.txt</Link>
	</Content>
	<Content Include="..\Markdown\Assets\Markdown\MarkdownToHTML_cs.txt">
		<Link>Markdown\Assets\Markdown\MarkdownToHTML_cs.txt</Link>
	</Content>
	<Content Include="..\Markdown\Assets\Markdown\MarkdownToPDF_cs.txt">
		<Link>Markdown\Assets\Markdown\MarkdownToPDF_cs.txt</Link>
	</Content>
	<Content Include="..\Markdown\Assets\Markdown\MarkdownToPPTX_cs.txt">
		<Link>Markdown\Assets\Markdown\MarkdownToPPTX_cs.txt</Link>
	</Content>
	<Content Include="..\Markdown\Assets\Markdown\PPTXToMarkdown_cs.txt">
		<Link>Markdown\Assets\Markdown\PPTXToMarkdown_cs.txt</Link>
	</Content>
  </ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="..\Markdown\Assets\Markdown\WordtoMD.docx">
			<Link>Markdown\Assets\Markdown\WordtoMD.docx</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="..\Markdown\Assets\Markdown\MarkdownToWord.md">
			<Link>Markdown\Assets\Markdown\MarkdownToWord.md</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="..\Markdown\Assets\Markdown\ExcelToMarkdown.xlsx">
			<Link>Markdown\Assets\Markdown\ExcelToMarkdown.xlsx</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="..\Markdown\Assets\Markdown\MarkdownToExcel.md">
			<Link>Markdown\Assets\Markdown\MarkdownToExcel.md</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="..\Markdown\Assets\Markdown\PPTXToMarkdown.pptx">
			<Link>Markdown\Assets\Markdown\PPTXToMarkdown.pptx</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="..\Markdown\Assets\Markdown\MarkdownToPPTX.md">
			<Link>Markdown\Assets\Markdown\MarkdownToPPTX.md</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
</Project>
